FROM docker.io/python:2.7

RUN apt-get update && apt install -y git yara

RUN git clone https://github.com/volatilityfoundation/volatility.git

RUN cd volatility && python setup.py build && python setup.py install

RUN python -m pip install pycrypto distorm3

CMD ["/bin/bash"]
