FROM docker.io/python:slim

RUN python -m venv /venv
ENV PATH=/venv/bin:$PATH

RUN apt update && apt install -y git gcc g++ libsnappy-dev

RUN python -m pip install wheel

RUN git clone https://github.com/volatilityfoundation/volatility3.git

RUN cd volatility3 && python -m pip install -r requirements.txt && python setup.py build && python setup.py install

FROM docker.io/python:slim
COPY --from=0 /venv /venv
ENV PATH=/venv/bin:$PATH

CMD ["/bin/bash"]
